config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get     "/articles", to: "articles#index"
  post    "/articles", to: "articles#create"
  get     "/articles/new", to: "articles#new", as: :new_article
  get     "/articles/:id/:action", to: "articles#edit", as: :edit_article
  get     "/articles/:id", to: "articles#show", as: :article
  post    "/articles/:id/vote/:type", to: "articles#vote", as: :vote
  patch   "/articles/:id", to: "articles#update"
  put     "/articles/:id", to: "articles#update"
  delete  "/articles/:id", to: "articles#destroy"

  #resources :articles
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!

  def new
    @article = Article.new
  end

  def create
    #Article.create(article_params)
  end

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def vote
    article = Article.find(params[:id])
    if params[:type] == "like"
        article.likes += 1
        article.save
    elsif params[:type] == "dislike"
        article.dislikes += 1
        article.save
    end
    redirect_to article_path(id: article.id)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy!
    redirect_to articles_path
  end

  def article_params
    #[:name, :body]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  # Homepage
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/index.html.erb
<div align="center">

<% @articles.each do |article| %>


  <div>
    <h1>
    <%= article.name %>
    </h1>
  </div>
  <div>
    <h3>
    <%= article.body %>
    </h3>
  </div>
  <div>
    <h3>
      <%= link_to "Likes", vote_path(id: article.id, type: "like"), method: :post %>: <%= article.likes.to_i %> <%= link_to "Dislikes", vote_path(id: article.id, type: "dislike"), method: :post %>: <%= article.dislikes.to_i %>
    </h3>
  </div>

<% end %>
<%= link_to "<<home>>", root_path %>
</div>

app/views/articles/show.html.erb
<div align="center">
  <div>
    <h1>
    <%= @article.name %>
    </h1>
  </div>
  <div>
    <h3>
    <%= @article.body %>
    </h3>
  </div>
  <div>
    <h3>
    <%= link_to "Likes", vote_path(id: @article.id, type: "like"), method: :post %>: <%= @article.likes.to_i %> <%= link_to "Dislikes", vote_path(id: @article.id, type: "dislike"), method: :post %>: <%= @article.dislikes.to_i %>
    </h3>
  </div>
  <%= link_to "<<back", articles_path %>
</div>

app/views/home/index.html.erb
<h1 align="center"> Hello, you are home <3</h1>

<h3 align="center"> <%= link_to "View all of our articles", articles_path %> or click on one (below) <h3>

<div align="center">
 List of articles:

  <% Article.all.each do |article| %>
    <% if article %>
      <div>
        <%= link_to article.name, article_path(id: article.id) %>
      </div>
     <%end %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkeaRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<% if current_user %>
<div align="right">
<%= link_to "My profile", edit_user_registration_path  %>
<p/>
<%= link_to "Logout",  destroy_user_session_path, method: :delete  %>
</div>
<% end %>